apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajkot-hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rajkot-hospital
  template:
    metadata:
      labels:
        app: rajkot-hospital
    spec:
      containers:
      - name: rajkot-hospital
        image: 572679073520.dkr.ecr.ap-south-1.amazonaws.com/ecrpush
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: rajkot-hospital-service
spec:
  selector:
    app: rajkot-hospital
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 32500
    protocol: TCP
